name: release

on:
  push:
    tags:
      - '*'

jobs:
  release-job:
    name: Build Release Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/buildroot-build
        with:
          defconfig: "wsap3825_doom_defconfig"
          version: "2023.02.5"
      - name: Pack Release Artifact
        run: tar cJf wsap3825-doom-output.tar.xz output
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: wsap3825-doom-output.tar.xz
          asset_name: wsap3825-doom-output.tar.xz
          asset_content_type: application/x-xz
